import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {localStorage} from '../scripts/local-storage.mjs';import worker from '../dist/server/index.js';
test('password gate, shared state, photo protection, persistence and undo',async()=>{const root=mkdtempSync(tmpdir()+'/ultra-test-');let storage=localStorage(root);let env={...storage,APP_PASSWORD:'test-only-password',SESSION_SECRET:'test-only-session-key-should-be-long'};const call=(path,method='GET',body,cookie,extra={})=>worker.fetch(new Request('https://example.test'+path,{method,headers:{'X-Ultra-Request':'1',...(cookie?{Cookie:cookie}:{}),...extra},body}),env);try{
 assert.equal((await call('/api/state')).status,401);assert.equal((await call('/app.js')).status,401);assert.equal((await call('/photos/crew-at-sunset.jpg')).status,401);assert.match(await(await call('/')).text(),/Your password/);
 assert.equal((await call('/api/login','POST',JSON.stringify({password:'wrong'}))).status,401);
 const login=()=>call('/api/login','POST',JSON.stringify({password:'test-only-password'}));const a=await login(),b=await login();assert.equal(a.status,200);const c1=a.headers.get('set-cookie').split(';')[0],c2=b.headers.get('set-cookie').split(';')[0];assert.match(a.headers.get('set-cookie'),/HttpOnly.*SameSite=Strict.*Secure/);
 assert.equal((await call('/api/activities/coach','DELETE',undefined,c1,{Origin:'https://evil.test'})).status,403);
 let form=new FormData();form.set('kind','strava');form.set('url','https://strava.com.evil.test/activities/12');assert.equal((await call('/api/activities/coach','POST',form,c1)).status,400);
 form=new FormData();form.set('kind','strava');form.set('url','https://www.strava.com/activities/123');assert.equal((await call('/api/activities/coach','POST',form,c1)).status,200);let saved=await(await call('/api/state','GET',undefined,c2)).json();assert.equal(saved.activities[0].id,'coach');
 form=new FormData();form.set('kind','photo');form.set('photo',new Blob([new Uint8Array([255,216,255,224,1,2,3])],{type:'image/jpeg'}),'photo.jpg');assert.equal((await call('/api/activities/sunrise','POST',form,c2)).status,200);assert.equal((await call('/api/photos/sunrise')).status,401);assert.equal((await call('/api/photos/sunrise','GET',undefined,c1)).status,200);
 storage.close();storage=localStorage(root);env={...env,...storage};assert.equal((await(await call('/api/state','GET',undefined,c1)).json()).activities.length,2);
 assert.equal((await call('/api/activities/coach','DELETE',undefined,c2)).status,200);await call('/api/import','POST',JSON.stringify({ids:['coach','rest']}),c1);saved=await(await call('/api/state','GET',undefined,c1)).json();assert(!saved.activities.some(x=>x.id==='coach'));assert(saved.activities.some(x=>x.id==='rest'));assert(saved.knownIds.includes('coach'));
 assert.equal((await call('/api/state','GET',undefined,c1+'tampered')).status,401);assert.match((await call('/api/logout','POST',undefined,c1)).headers.get('set-cookie'),/Max-Age=0/);
 for(let i=0;i<10;i++)await call('/api/login','POST',JSON.stringify({password:'wrong'}));assert.equal((await login()).status,429);
 }finally{storage.close();rmSync(root,{recursive:true,force:true})}});
